nelmio_api_doc:
    documentation:
        info:
            title: Facebook Inc
            description: My perfect app
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/v1(?!/doc$) # Accepts routes under /api except /api/doc
