# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
  - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.2

# Update composer
before-install:
  - composer self-update

install:
  - composer install
  - cp .env.test .env
  - echo 'DATABASE_URL=mysql://travis:@127.0.0.1:3306/test_db' >> .env
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:migrations:migrate -n

script:
  - php bin/phpunit